### ISSUE TITLE
.dockerignore white-list pattern causes error

### ISSUE THREAD

**Issue by 1Mill** [kreuzwerker/terraform-provider-docker#249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

`Terraform v1.0.2`

### Affected Resource(s)

* `docker_registry_image`

### Terraform Configuration Files

Folder structure:
* app
  * empty
  * .dockerignore
  * Dockerfile
  * main.tf

empty
```
# This this an empty file
```

.dockerignore
```
*

!empty
```

Dockerfile
```
FROM scratch
COPY empty /empty
```

main.tf
```hcl
terraform {
  required_version = "~> 1.0"

  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = ">= 2.14.0"
    }
  }
}

provider "docker" {...}

resource "docker_registry_image" "this" {
  name = "my-image-name"

  build {
    context = abspath(path.module)
  }
}
```

### Expected Behaviour

Successfully build and publish image to registry. 

### Actual Behaviour

```bash
Error: Error building docker image: Error response from daemon: Cannot locate specified Dockerfile: Dockerfile
```

### Steps to Reproduce

1. `terraform init`
1. `terraform apply -auto-approve`

### Important Factoids

* The error only occurs when using the white-list pattern in the `.dockerignore` file. This implies to me that something is wrong with the `*` interpretation / pattern in the module.

**Comment by JavaScriptBach** [comment]
I think the actual issue is that Dockerfiles must not be excluded before being passed to the API. I ran into a similar issue today (`docker build` worked fine, but missing Dockerfiles when using this provider) and finally resolved it by changing .dockerignore to not exclude Dockerfiles.

If you take a look at the [CLI code](https://github.com/docker/cli/blob/c780f7c4abaf67034ecfaa0611e03695cf9e4a3e/cli/command/image/build.go#L264), you can see it's excluding Dockerfile and .dockerignore before passing them to the API, along with a bunch of other complicated logic that has no equivalent in the provider. My guess is we need to implement something similar in order for this provider to behave more comparably to `docker build`.
