### ISSUE TITLE
Deployment of single container results in `Error: container failed to be in running state`

### ISSUE THREAD

**Issue by mplattner** [kreuzwerker/terraform-provider-docker#475]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

```
Terraform v1.3.2
on windows_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.22.0
```

Docker version: 20.10.21, installed via convenience script on Ubuntu 22.04

### Affected Resource(s)

* `docker_container.foo`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.22.0"
    }
  }
}

provider "docker" {
  host = "ssh://root@192.168.111.222"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

# Find the latest Ubuntu precise image.
resource "docker_image" "ubuntu" {
  name = "ubuntu:latest"
}

resource "docker_container" "foo" {
  name  = "foo"
  image = docker_image.ubuntu.image_id
  start = true
}
```

### Debug Output

https://gist.github.com/mplattner/2087c85734dbb882abce1ce57a9d4288

### Expected Behaviour

Create image ✔️
Start the container ❌

### Actual Behaviour

```
╷
│ Error: container failed to be in running state
│
│   with docker_container.foo,
│   on docker.tf line 20, in resource "docker_container" "foo":
│   20: resource "docker_container" "foo" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

**Comment by Junkern** [comment]
The behaviour is expected and not an issue with the provider itself.
The terraform code of yours is an equivalent to running `docker run ubuntu`. This command also exits immediately since we did not provide any command to run.
Please use the [command](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#command) attribute to specify a command to run.

Or you use `must _run = false` to get rid of the error message (but then you still won't have a running container, as it exits immediately without a proper command)

**Comment by mplattner** [comment]
Oh, I see, thanks 👍
My misunderstanding was due to the example image (`ubuntu`) not having a default command, as many other containers have.
