### ISSUE TITLE
Support runtime parameter for docker_container

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#85]
<i>This issue was originally opened by @captn3m0 as https://github.com/hashicorp/terraform-provider-docker/issues/142. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
### Terraform Version
`0.11.13`

### Affected Resource(s)

- `docker_container`

### Terraform Configuration Files
```hcl
resource docker_container {
  name = "c"
  runtime = "nvidia"
  image ="..."
}
```

### Expected Behavior
The runtime parameter should be supported, since it is part of the docker run command.

### Actual Behavior
The runtime argument is unsupported

### References

From `docker --help`:

```
--runtime string                 Runtime to use for this container
```

This is primarily useful if you are using the nvidia runtime alongside runc.

**Comment by fimbulwint** [comment]
This would be great to have. We are currently running containers using the `Sysbox` runtime and we have to use a messy workaround with `null_resource`s to make it work.

Being able to just pass the runtime to `docker_container` would make things much simpler for us.

**Comment by mavogel** [comment]
will be implemented in #142 . Closing for now

**Comment by captn3m0** [comment]
The `--runtime` parameter was outdated very quickly, and is no longer recommended except for specific usecases. For Docker 19.03+, the `--gpus` parameter (#63) is the much cleaner and nicer approach.

[This comment](https://github.com/NVIDIA/nvidia-docker/issues/1268#issuecomment-632692949) explains the differences. Most guides, [such as the ArchLinux Wiki](https://wiki.archlinux.org/title/Docker#Run_GPU_accelerated_Docker_containers_with_NVIDIA_GPUs) recommend using the toolkit if you can. It is a much lighter approach, and better integrated with Docker overall.

There's still some cases where it might be better to use `--runtime`, but most aren't applicable here:

- Running builds with GPUs. (doesn't apply here)
- Running on Kubernetes, since that doesn't support `--gpus` parameter yet (doesn't apply here)
- Running Docker < 19.03.  (Came out 2021-02-01). This might apply here.

Just something to consider. As a provider user, I'll be content with just #63. Keeping both might cause confusion down the line.

**Comment by matifali** [comment]
Any update?
